# AGGREGATE FUNCTIONS:

1)SUM
2)PROD
3) MEAN
4) STD
5)VAR
6)MIN
7)MAX
8)argmin and argmax

# SUM

In [1]:
import numpy as np
a=np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [2]:
np.sum(a) ##-->b=np.sum(a)   b


90

In [3]:
b=np.random.randint(2,20,6)
b

array([18, 15,  7, 18, 11, 10])

In [4]:
np.sum(b)

79

# MIN()AND MAX():

In [5]:
a=np.random.randint(22,100,30)
print(a)
np.min(a),np.max(a)

[46 32 67 86 56 22 47 91 62 88 28 40 49 68 65 33 72 44 40 85 83 29 85 67
 99 42 99 71 90 80]


(22, 99)

In [6]:
(np.min(a),np.max(a),np.sum(a))

(22, 99, 1866)

In [7]:
a.min()  #-->like this also we can give

22


# IN TWO DIMENSIONAL ARRAY

In [8]:
a=np.random.randint(2,10,(2,3))
print(a)
print(a.sum(),a.min(),a.max())

[[4 5 3]
 [4 3 2]]
21 2 5


In [9]:
a.min(axis=0)  ##---> axis=0 column la min value it will return

array([4, 3, 2])

In [10]:
a.max(axis=1)#--->axis=1 row la max value return pannum

array([5, 4])

In [11]:
b=a.sum(axis=1)#row la sum panni return pannum
print(b)
c=a.sum(axis=0)#column la sum panni return agum
print(c)

[12  9]
[8 8 5]


# PRODUCT():

In [12]:
c=np.arange(3,21)
b=c.reshape(6,3)
print(b)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]


In [13]:
np.prod(b)

1096417280

In [15]:
np.prod([[2,3],[2,1]])

12

# MEAN(:

In [71]:
a=np.array([[3,4],[10,15],[10,20]])#-->RETURNS MEAN VALUE
a.mean()#-->3.5+12.5+15.0=31/3=10.33333

10.333333333333334

In [74]:
a=np.mean([3,4])
b=np.mean([10,15])
c=np.mean([10,20])
print(a ,b ,c)

3.5 12.5 15.0


# STANDARD DEVIATION():

In [75]:
a=np.array([[22,3,4,5,5],[1,2,3,4,5]])
a.std()


5.678027826631356

# VARIANCE



In [76]:
a.var()

32.24000000000001

In [77]:
print(int(np.var(a)))

32



# ARGMAX() AND ARGMAX()

In [80]:
arr=np.random.randint(2,10,10)
arr

array([9, 2, 9, 7, 7, 9, 2, 5, 8, 4])

In [81]:
arr.argmax()

0

In [82]:
arr.argmin()

1

# MEDIAN


In [84]:
np.median(arr)

7.0

# INDEXING AND SORTING

# LAB EX 2:

# SORT():

In [92]:
import numpy as np   #--->sort the elements
so=np.random.randint(2,30,15)
print(so)
b=np.sort(so)
print("the sorted array is",b)

[ 8 22 25 17  9 18 17 13 21 16 21 13 23 17  9]
the sorted array is [ 8  9  9 13 13 16 17 17 17 18 21 21 22 23 25]


# ARGSORT():

In [95]:
c=np.argsort(so)#--->argsort vanthu atho index position ah sort panni taranum
print(c)

[ 0  4 14  7 11  9  3  6 13  5  8 10  1 12  2]


# SORTING ALONG ROWS AND COLUMNS

In [98]:
rand=np.random.RandomState(42)
x=rand.randint(1,20,(5,4))
print(x)

[[ 7 15 11  8]
 [ 7 19 11 11]
 [ 4  8  3  2]
 [12  6  2  1]
 [12 12 17 10]]


# sort each column of x

In [99]:
np.sort(x,axis=0) #-->sort the above matrix in column and returns

array([[ 4,  6,  2,  1],
       [ 7,  8,  3,  2],
       [ 7, 12, 11,  8],
       [12, 15, 11, 10],
       [12, 19, 17, 11]])

# sort each row of x

In [100]:
np.sort(x,axis=1) #-->sort the above matrix in row and returns

array([[ 7,  8, 11, 15],
       [ 7, 11, 11, 19],
       [ 2,  3,  4,  8],
       [ 1,  2,  6, 12],
       [10, 12, 12, 17]])

# REVERSE ORDER SORTING

In [101]:
np.sort(-x)#--->matrix +ve all -ve ah change agum   then reverse la print agum

array([[-15, -11,  -8,  -7],
       [-19, -11, -11,  -7],
       [ -8,  -4,  -3,  -2],
       [-12,  -6,  -2,  -1],
       [-17, -12, -12, -10]])

# SORTING ARRAY ALPHABETICALLY


In [103]:
arr=np.array(['austalia','japan','china','swiss','angalo'])
print(np.sort(arr))

['angalo' 'austalia' 'china' 'japan' 'swiss']


# SORTING BOOLEAN ARRAY 

# arr=np.array([True,False,False,True])
print(np.sort(arr))#---->it returns false because 0 then true

# SORTING 2D ARRAY

In [107]:
arr=np.array([[10,8,9],[4,3,2]])
print(np.sort(arr))

[[ 8  9 10]
 [ 2  3  4]]


# LEXSORT():

In [109]:
a=(['ziva','renu','ram','geetha','vino'])
b=([33,22,67,89,10])
ind=np.lexsort((a,b))#-->a,b na a va vachi kittu b ah sort pannum b,a na b ah vachi kittu a va sort pannum
print(ind)

[4 1 0 2 3]


In [110]:
a=(['ziva','renu','ram','geetha','vino'])
b=([33,22,67,89,10])
ind=np.lexsort((b,a))#-->a,b na a va vachi kittu b ah sort pannum b,a na b ah vachi kittu a va sort pannum
print(ind)

[3 2 1 4 0]


In [111]:
#-->if suppose oru ethula same values eruinthuchuna athuku kela eruka values ah pakkum
#eg:ziva two times eruku so namba athuku keza eruka value va pakkanum ziva 33 then ziva 9
# which is less 9 so 5th pos la ziva eruku atha print pannum
    
a=(['ziva','renu','ram','geetha','vino','ziva'])
b=([33,22,67,89,10,9])
ind=np.lexsort((b,a))#-->a,b na a va vachi kittu b ah sort pannum b,a na b ah vachi kittu a va sort pannum
print(ind)

[3 2 1 4 5 0]


In [112]:
#-->if suppose oru ethula same values eruinthuchuna athuku kelaum same values ah then
#eg:ziva two times eruku so namba athuku keza eruka value va pakkanum ziva 33 then ziva 33
# so appo ziva oda index position pakkum so zero the five eruku 
a=(['ziva','renu','ram','geetha','vino','ziva'])
b=([33,22,67,89,10,33])
ind=np.lexsort((b,a))
print(ind)

[3 2 1 4 0 5]


# INDEXING

In [114]:
a=np.array([3,4,7,2,9,3,1,9,5,3,2,3,99])
print(a[10])

2


In [116]:
print(a[10]+a[11])

5


# ACCESSSING 2D ARRAY

In [118]:
b=np.array([[3,5,6,7],[3,2,1,5]])
b[0,3]

7

In [119]:
b[1,2]

1

# ACCESSING 3D ARRAY

In [125]:
arr=np.array([[[2,3,4],[4,3,2]],[[2,4,5],[6,8,9]]])
arr[1,1,0]

6

In [127]:
arr[0,1,2]

2

# WHERE

In [129]:
obj=np.array([22,33,4,55,66])
print(np.where(obj>22))#-->index pos tha return pannum

(array([1, 3, 4], dtype=int64),)


# NON ZERO

In [2]:
import numpy as np
obj=np.array([22,33,4,55,66])
print(obj)
print(obj.nonzero())

[22 33  4 55 66]
(array([0, 1, 2, 3, 4], dtype=int64),)


# HIERACHICAL INDEXING

In [15]:
import pandas as pd
df=pd.read_csv('C:/Users/HP/Downloads/homelessness.csv')
print(df) #-->all the  values will display

    Unnamed: 0              region                 state  individuals  \
0            0  East South Central               Alabama       2570.0   
1            1             Pacific                Alaska       1434.0   
2            2            Mountain               Arizona       7259.0   
3            3  West South Central              Arkansas       2280.0   
4            4             Pacific            California     109008.0   
5            5            Mountain              Colorado       7607.0   
6            6         New England           Connecticut       2280.0   
7            7      South Atlantic              Delaware        708.0   
8            8      South Atlantic  District of Columbia       3770.0   
9            9      South Atlantic               Florida      21443.0   
10          10      South Atlantic               Georgia       6943.0   
11          11             Pacific                Hawaii       4131.0   
12          12            Mountain                 

In [44]:
print(df.head(10)#-->if u specify the head it returns if not 
      # ne specify pannalana just user ku show panna silla columns mattum display pannum4

   Unnamed: 0              region                 state  individuals  \
0           0  East South Central               Alabama       2570.0   
1           1             Pacific                Alaska       1434.0   
2           2            Mountain               Arizona       7259.0   
3           3  West South Central              Arkansas       2280.0   
4           4             Pacific            California     109008.0   
5           5            Mountain              Colorado       7607.0   
6           6         New England           Connecticut       2280.0   
7           7      South Atlantic              Delaware        708.0   
8           8      South Atlantic  District of Columbia       3770.0   
9           9      South Atlantic               Florida      21443.0   

   family_members  state_pop  
0           864.0    4887681  
1           582.0     735139  
2          2606.0    7158024  
3           432.0    3009733  
4         20964.0   39461588  
5          3250.0    

In [20]:
df.columns

Index(['Unnamed: 0', 'region', 'state', 'individuals', 'family_members',
       'state_pop'],
      dtype='object')

In [45]:
df_ind3=df.set_index(['region','state','individuals'])## display wt iam giving first
df_ind3.head(10)

Unnamed: 0  \
region             state                individuals               
East South Central Alabama              2570.0                0   
Pacific            Alaska               1434.0                1   
Mountain           Arizona              7259.0                2   
West South Central Arkansas             2280.0                3   
Pacific            California           109008.0              4   
Mountain           Colorado             7607.0                5   
New England        Connecticut          2280.0                6   
South Atlantic     Delaware             708.0                 7   
                   District of Columbia 3770.0                8   
                   Florida              21443.0               9   

                                                     family_members  state_pop  
region             state                individuals                             
East South Central Alabama              2570.0                864.0    4887681  
Pacific            Alaska               1434.0                582.0     735139  
Mountain           Arizona              7259.0               2606.0    7158024  
West South Central Arkansas             2280.0                432.0    3009733  
Pacific            California           109008.0            20964.0   39461588  
Mountain           Colorado             7607.0               3250.0    5691287  
New England        Connecticut          2280.0               1696.0    3571520  
South Atlantic     Delaware             708.0                 374.0     965479  
                   District of Columbia 3770.0               3134.0     701547  
                   Florida              21443.0              9587.0   21244317

In [46]:
df_ind3=df.set_index(['region','state','individuals','family_members'])## display wt iam giving first
df_ind3.head(10)

Unnamed: 0  \
region             state                individuals family_members               
East South Central Alabama              2570.0      864.0                    0   
Pacific            Alaska               1434.0      582.0                    1   
Mountain           Arizona              7259.0      2606.0                   2   
West South Central Arkansas             2280.0      432.0                    3   
Pacific            California           109008.0    20964.0                  4   
Mountain           Colorado             7607.0      3250.0                   5   
New England        Connecticut          2280.0      1696.0                   6   
South Atlantic     Delaware             708.0       374.0                    7   
                   District of Columbia 3770.0      3134.0                   8   
                   Florida              21443.0     9587.0                   9   

                                                                    state_pop  
region             state                individuals family_members             
East South Central Alabama              2570.0      864.0             4887681  
Pacific            Alaska               1434.0      582.0              735139  
Mountain           Arizona              7259.0      2606.0            7158024  
West South Central Arkansas             2280.0      432.0             3009733  
Pacific            California           109008.0    20964.0          39461588  
Mountain           Colorado             7607.0      3250.0            5691287  
New England        Connecticut          2280.0      1696.0            3571520  
South Atlantic     Delaware             708.0       374.0              965479  
                   District of Columbia 3770.0      3134.0             701547  
                   Florida              21443.0     9587.0           21244317

In [37]:
df_ind3_region=df_ind3.loc[['Pacific','Mountain']]
df_ind3_region

Unnamed: 0  family_members  state_pop
region   state      individuals                                       
Pacific  Alaska     1434.0                1           582.0     735139
         California 109008.0              4         20964.0   39461588
         Hawaii     4131.0               11          2399.0    1420593
         Oregon     11139.0              37          3337.0    4181886
         Washington 16424.0              47          5880.0    7523869
Mountain Arizona    7259.0                2          2606.0    7158024
         Colorado   7607.0                5          3250.0    5691287
         Idaho      1297.0               12           715.0    1750536
         Montana    983.0                26           422.0    1060665
         Nevada     7058.0               28           486.0    3027341
         New Mexico 1949.0               31           602.0    2092741
         Utah       1904.0               44           972.0    3153550
         Wyoming    434.0                50           205.0     577601

In [48]:
df_ind3_region_state=df_ind3.loc[[("Pacific","Alaska",1434,582.0),
                                  ("Mountain","Idaho",1297,715.0)]]
df_ind3_region_state

Unnamed: 0  state_pop
region   state  individuals family_members                       
Pacific  Alaska 1434.0      582.0                    1     735139
Mountain Idaho  1297.0      715.0                   12    1750536

In [38]:
df_ind3_region_state=df_ind3.loc[[("Pacific","Alaska",1434),
                                  ("Mountain","Idaho",1297)]]
df_ind3_region_state

Unnamed: 0  family_members  state_pop
region   state  individuals                                       
Pacific  Alaska 1434.0                1           582.0     735139
Mountain Idaho  1297.0               12           715.0    1750536

In [40]:
df.iloc[7] # returns the both the rows and columns with the index

Unnamed: 0                     7
region            South Atlantic
state                   Delaware
individuals                708.0
family_members             374.0
state_pop                 965479
Name: 7, dtype: object

In [41]:
df.iloc[[0,2],[0,1]]

Unnamed: 0              region
0           0  East South Central
2           2            Mountain

In [42]:
df.iloc[3]

Unnamed: 0                         3
region            West South Central
state                       Arkansas
individuals                   2280.0
family_members                 432.0
state_pop                    3009733
Name: 3, dtype: object

In [55]:
df.iloc[[0,9,7,1,2,3,4]]

Unnamed: 0              region       state  individuals  family_members  \
0           0  East South Central     Alabama       2570.0           864.0   
9           9      South Atlantic     Florida      21443.0          9587.0   
7           7      South Atlantic    Delaware        708.0           374.0   
1           1             Pacific      Alaska       1434.0           582.0   
2           2            Mountain     Arizona       7259.0          2606.0   
3           3  West South Central    Arkansas       2280.0           432.0   
4           4             Pacific  California     109008.0         20964.0   

   state_pop  
0    4887681  
9   21244317  
7     965479  
1     735139  
2    7158024  
3    3009733  
4   39461588

# PIVOT TABLE

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns #--> seaborn is just a visualization tool
titanic = sns.load_dataset('titanic')
titanic

In [58]:
x=pd.read_csv('"C:\Users\HP\Desktop/first year/FDS BOOK AND PPT/titanic dataset csv.csv')
x

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/HP/Desktop/first year/TITANIC DATA/titanic dataset.csv'