In [1]:
#num = nummerical
# py =python

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [32]:
import numpy as np # numpy is the package np = numpy
array = np.array([4,6,21,5])
print(array)

[ 4  6 21  5]


In [33]:
array.dtype

dtype('int32')

In [34]:
array.argmax()  #prints the index positoin of maximum value of the array

2

In [35]:
array.argmin() # prints the index position of minimum value of the array

0

In [36]:
array.max() # prints the maximum value of the array

21

In [37]:
array.min() # prints the minimum value of the array

4

In [39]:
array.argsort() # is is used to sort the array and return the sorted index position of the array

array([0, 3, 1, 2], dtype=int64)

In [45]:
array.any()

True

In [49]:
array.all()

True

In [5]:
import numpy as np
ma=[[5,5,5],[6,7,5],[7,6,5]]
np.array(ma)
# two dimensional array......

array([[5, 5, 5],
       [6, 7, 5],
       [7, 6, 5]])

In [10]:
ma3d=[[[3,3,3],[3,4,5],[4,3,2]],[[9,9,8],[8,7,6],[3,4,5]]]
np.array(ma)

array([[5, 5, 5],
       [6, 7, 5],
       [7, 6, 5]])

In [12]:
#array ----->returns evenly sapced in the given interval

In [16]:
a=np.arange(1,10,2)
print(a)
type(a)

[1 3 5 7 9]


numpy.ndarray

In [ ]:
# zeros and ones --->generate array of zeros and ones


In [22]:
np.zeros((5),dtype=int) # or np.zeros((5),int)

array([0, 0, 0, 0, 0])

In [43]:
np.ones((2,4,4),int) #(channel,row,column)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [18]:
#LINSPACE
#return evenly spaced numbers over a specified interval

In [29]:
np.linspace(1,10,num=5,dtype=int) #num=5 returns 5 numbers(it takes any random valuesr)

array([ 1,  3,  5,  7, 10])

In [30]:
#eye---->create an identity matrix


In [35]:

np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [1]:
#random---> numpy has many ways to create random number arrays
#random.rand(channel,row,column)

np.random.rand(7,2,6)


NameError: name 'np' is not defined

In [52]:
import numpy as np1
np1.random.rand(7,2,2)

array([[[0.91019446, 0.06458089],
        [0.43273979, 0.46639503]],

       [[0.17021741, 0.22511485],
        [0.67447928, 0.42504985]],

       [[0.32826601, 0.98582702],
        [0.36155273, 0.38851233]],

       [[0.78629881, 0.96673468],
        [0.46587964, 0.41564849]],

       [[0.91151045, 0.64644036],
        [0.76863888, 0.34587832]],

       [[0.36678574, 0.55394819],
        [0.62718604, 0.98655837]],

       [[0.44154804, 0.04452292],
        [0.47101386, 0.96404245]]])

In [55]:
#randn----> returns a sample from the standard normal distribution

np.random.randn(4,2,2)#-->any random values return agum

array([[[ 0.50783528,  0.76524579],
        [ 0.84624324, -0.99002063]],

       [[ 0.0712039 , -0.28505305],
        [ 1.50441808,  0.49234068]],

       [[ 1.95345318, -0.87562579],
        [-0.67820754, -2.16668753]],

       [[ 0.0023884 , -0.53072118],
        [-0.4950075 , -0.66487308]]])

In [61]:
#randint-->returns a random integer from low (inclusive)to high(excluisve)
np.random.randint(2,10)

7

In [3]:
import numpy as np
x=np.random.randint(2,10,2)
print(x)

[4 2]


In [68]:
#seed--->used to set the random state so that it can be reused
np.random.seed(42)# here 42 is constant dont change 
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [69]:
#array attributes and methods

In [72]:
arr=np.arange(25)
randarr=np.random.randint(0,30,100)
print(arr)
print(randarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[22 27 24 29  7 20 15 12 17 14 20 23 25 24 27 27 27 12  8 28 14 12  0 24
  6  8 23  0 11  7 23 10 18 16  7  2  2  0 26  4  9  6 25  8 27  6  8  7
 11  1  0 15 22 22 29 23  4  2 11  7 21 26  2  0  2  4 14 13  2  0  4 25
 22 13  6 26  8 14 14 25  9 27 12 18  6 16 19 28  3 29  4 22  6 12 14 10
 28  3 12  6]


In [ ]:
#reshape

In [73]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#max,min,argmax,argmin


In [74]:
randarr.max()

29

In [75]:
randarr.min()

0

In [76]:
randarr.argmax()

3

In [77]:
randarr.argmin()

22

In [78]:
#shape-->is an attribute that array 
arr.shape


(25,)

In [21]:
import numpy as np
arr=[[1,2,3],[2,3,4],[4,5,6]],[[1,2,3],[2,3,4],[4,5,6]],[[1,2,3],[2,3,4],[4,5,6]]
print(np.array(arr))

[[[1 2 3]
  [2 3 4]
  [4 5 6]]

 [[1 2 3]
  [2 3 4]
  [4 5 6]]

 [[1 2 3]
  [2 3 4]
  [4 5 6]]]


In [26]:

arr=np.arange(25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr.shape

(25,)

In [37]:
arr=np.array([[[3,4,2],[2,3,4]],[[9,8,7],[8,7,7]],[[9,8,0],[0,9,8]]])
arr

array([[[3, 4, 2],
        [2, 3, 4]],

       [[9, 8, 7],
        [8, 7, 7]],

       [[9, 8, 0],
        [0, 9, 8]]])

In [41]:
arr[2][1][2]

8

In [4]:
import numpy as np
arr=[[[4,5,6],[5,4,3],[3,4,5]],[[3,4,5],[4,4,5],[5,2,3]]]
print(np.array(arr))


[[[4 5 6]
  [5 4 3]
  [3 4 5]]

 [[3 4 5]
  [4 4 5]
  [5 2 3]]]


In [6]:
arr=[[4,5,6],[5,4,3],[3,4,5]]
print(np.array(arr))

[[4 5 6]
 [5 4 3]
 [3 4 5]]


In [24]:
arr[:2][1:]

[[5, 4, 3]]

In [25]:
np.empty(5)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.03346878e-311,
       0.00000000e+000])